USE rugoing;

CREATE TABLE `events` (
  `eventid` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `location` varchar(100) NOT NULL,
  `timeofevent` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `url` varchar(100) NOT NULL,
  `synopsis` varchar(1000) NOT NULL,
  `category` varchar(100) NOT NULL,
  `target_audience` varchar(1000) NOT NULL,
  `hashtag` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`eventid`)
) ENGINE=InnoDB AUTO_INCREMENT=780 DEFAULT CHARSET=latin1;


insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (1,'meet and greet','ece 250','2010-10-06 00:01:00','','','','','adf');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (2,'meet and greet','bio 120','2010-11-17 04:05:00','','','','',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (3,'nano tech ','ece 100','2010-11-05 00:04:00','','','','',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (4,'pharma','phram 192','2010-11-22 01:00:00','','','','',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (6,'midterm software engineering','core 538','2010-11-04 00:02:00','','','','',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (7,'final english 101','arc 250','2010-12-21 04:02:00','','','','',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (8,'testblah','asdf','2010-10-05 00:04:00','','','','',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (11,'hey','hey','2010-12-03 00:50:00','hey','hey','hey','hey',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (12,'hey','hey','2010-12-03 00:04:34','hey','hey','hey','hey',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (14,'b','b','2011-05-01 08:30:52','b','b','b','b',null);
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (15,'Rutgers Football Game1','busch campus','2010-12-28 15:36:00','www.rutgers.edu','great event!','other','students','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (16,'Rutgers Football Game1','busch campus','2010-12-30 15:35:00','www.rutgers.edu','great event!','other','students','hash2');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (692,'Justice and Java: Expressions Against Gender Violence Coffeehouse','Douglass Campus Center,Douglass Campus,New Brunswick,NJ US','2010-12-06 19:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67729','The coffeehouse will include a night of instrumental, poetic, dance, spoken word, and other artistic performances  that will aim to raise awareness about issues surrounding gender-based violence, specifically in relation to the intersections of gender-violence and militarism.','Performance','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (693,'Skills for the 21st Century Workforce: the evolving education and training systems of India and China and the implications ','Off-Campus Location/S,Off Campus Campus,Edison,NJ US','2010-12-06 18:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67714','China and India are the two most populous and rapidly growing economies.   China and India have not limited their development to low-end manufacturing and services.  Learn how the workforce in China and India is educated and the impact on the American workforce.','Meeting','Current Students,Researchers,Donors & Supporters,Graduate Students,Faculty,Staff,Alumni,General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (694,'Rutgers Wind Ensemble','Nicholas Music Center,Douglass Campus,New Brunswick,NJ US','2010-12-13 20:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65932','Eugene Coporon, conductor','Performance','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (695,'Seminar:  Applications of DNA Stable Isotope Probing To Detangle N Utilization By Phytoplankton And Bacteria In Coastal Subtropical Marine Environments','Environmental & Natural Resource Sciences Bldg,George H. Cook Campus,New Brunswick,NJ US','2010-12-15 14:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67719','Presentation of Applications of DNA Stable Isotope Probing in Coastal Subtropical Marine Environments.','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (696,'Mindfulness Meditation','Rutgers Student Center,College Avenue Campus,New Brunswick,NJ US','2010-12-15 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66904','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required. ','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (697,'Scientific evidence and new recommendations for vitamin D and calcium : 2010 Institute of Medicine report','Davison Hall,Douglass Campus,New Brunswick,NJ US','2010-12-15 14:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67331','Scientific evidence and new recommendations for vitamin D and calcium : 2010 Institute of Medicine report','Talk, Lecture, Seminar','Current Students,Researchers,Donors & Supporters,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (698,'Dear Santa','Busch Campus Center,Busch Campus,Piscataway,NJ US','2010-12-11 19:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67742','Kappa Phi Lambda will be hosting its annual Dear Santa Toy Drive where collected toys will be donated. Activities will range from building a bear to making a gingerbread house. Last year Kappa Phi Lambda donated over 50 toys to the Bristol-Myers Squibb Children''s Hospital.','Special Event','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (699,'Workshop: Teen Drawing Society','Voorhees Hall Incl Zimmerli Art Museum,College Avenue Campus,New Brunswick,NJ US','2010-12-11 15:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67174','For ages 14-19.
','Art','Prospective Students,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (700,'Lecture-The Rebbe:The Life and Afterlife of Menachem Mendel Schneerson','Douglass Campus Center,Douglass Campus,New Brunswick,NJ US','2010-12-08 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66583','The Allen and Joan Bildner Center for the Study of Jewish Life presents a lecture by Samuel Heilman, distinguished Professor of Sociology at Queens College and holder of the Harold Proshansky Chair in Jewish Studies at the Graduate Center of the City University of New York. ','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (701,'Mindfulness Meditation','Rutgers Student Center,College Avenue Campus,New Brunswick,NJ US','2010-12-08 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66903','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required. ','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (702,'Workshop: Zimmerli Drawing Society','Voorhees Hall Incl Zimmerli Art Museum,College Avenue Campus,New Brunswick,NJ US','2010-12-11 12:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67169','The Zimmerli Drawing Society offers advanced and beginning artists an opportunity to draw both from the live model and from the Museums vast collections.','Art','Current Students,Visitors,Undergraduate Students,Graduate Students,Faculty,Staff,Alumni,General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (703,'**CANCELED**Cost Containment: The Next Steps After Health Reform','Institute For Health Sciences,College Avenue Campus,New Brunswick,NJ US','2010-12-09 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66372','John F. Holahan, PhD, Director of the Health Policy Research Center, The Urban Institute','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (704,'Social Work Across Borders','Woodlawn Mansion,Douglass Campus,New Brunswick,NJ US','2010-12-09 15:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67778','Professor Rebecca Davis will discuss the evolution of the field of social work as it relates to immigrant populations. She will present her own empirical research on social work practices in sending and receiving communities.','Talk, Lecture, Seminar','Current Students,Researchers,Undergraduate Students,Graduate Students,Faculty','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (705,'Turning Around Chronically Low-Performing Schools','Off-Campus Location/S,Off Campus Campus,Vineland,NJ US','2010-12-07 08:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67621','This free Educational Forum event is hosted in collaboration with The New Jersey Department of Education, Rutgers, The State University of New Jersey, and the Public Education Institute and features Dr. Marlene Darwin, with the American Institute for Research.','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (706,'Spirit Nite','Catholic Center,College Avenue Campus,New Brunswick,NJ US','2010-12-07 20:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66819','Weekly topical meeting that also includes music, prayer, praise and fellowship.','Special Event','Current Students,Commuters,Undergraduate Students','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (707,'SSRC graduate Fellowships: A Presentation of the DPDF and IDRF Fellowships','Alexander Library,College Avenue Campus,New Brunswick,NJ US','2010-12-08 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67738','SSRC Program Officers will provide information on their graduate fellowships including tips and advice on writing a competitive application','Talk, Lecture, Seminar','Graduate Students','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (708,'GSE Alumni Association Holiday Party and Networking','Rutgers Club,College Avenue Campus,New Brunswick,NJ US','2010-12-07 17:45:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67734','Join GSE alumni, students, and faculty for socializing, networking, complimentary hors d''oeuvres and beverages, music, and fun!

There is no charge for this event.  A cash bar and buffet dinner will be available.','Career','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (709,'Men''s Basketball vs. Marist','Louis Brown Athletic Center (Rac),Livingston Campus,Piscataway,NJ US','2010-12-07 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67371','Men''s basketball takes on Marist at the RAC at 7:30 pm.','Sporting Event','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (710,'KPL & SBP Blood Drive','Busch Campus Center,Busch Campus,Piscataway,NJ US','2010-12-07 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67741','Kappa Phi Lambda and Sigma Beta Rho are having a blood drive on Tuesday, December 7th from 12 PM - 4:30 PM in the Busch Campus Center Multipurpose Room. Donors receive a free t-shirt and snacks. ','Other','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (711,'Ph.D. Fellowships in Educational Measurement & Statistics Information Session','Graduate School Of Education Building,College Avenue Campus,New Brunswick,NJ US','2010-12-07 17:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67756','Hosted by Dr. Jimmy de la Torre.

For more information and to register, email: ep@gse.rutgers.edu.','Career','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (712,'Mindfulness Meditation','Busch Campus Center,Busch Campus,Piscataway,NJ US','2010-12-07 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66870','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required.','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (713,'RU Army ROTC Blood Drive','Army Rotc,College Avenue Campus,New Brunswick,NJ US','2010-12-07 11:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67535','Commemorate Pearl Harbor Day by donating blood. The NY/NJ Blood Services Blood Mobile will be at the Army ROTC Building all day.  ','Special Event','Current Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (714,'F2F Networking Made Simple:Alumni Program','Winants Hall,College Avenue Campus,New Brunswick,NJ US','2010-12-08 15:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67016','Learn how to cultivate relationships to build your network and make career connections.','Career','Alumni','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (715,'Making New Materials from Synthetically Modified Biomolecules','Wright Chemistry Building,Busch Campus,Piscataway,NJ US','2010-12-07 11:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66625','CCB Colloquium presentation by Dr. Matthew B. Francis, University of California at Berkeley.','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (716,'CETP Inhibitors: the good, the bad and the off-target effects','Davison Hall,Douglass Campus,New Brunswick,NJ US','2010-12-08 14:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67135','CETP Inhibitors: the good, the bad and the off-target effects','Talk, Lecture, Seminar','Current Students,Researchers,Undergraduate Students,Graduate Students,Faculty,Staff,Alumni','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (717,'New optimal microstructures and sharp restrictions on the attainable Hashin-Shtrikman bounds for Multiphase Composite Materials','School Of Engineering Building,Busch Campus,Piscataway,NJ US','2010-12-08 15:15:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66603','New optimal microstructures and sharp restrictions on the attainable Hashin-Shtrikman bounds for Multiphase Composite Materials','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (718,'New Jersey Jobs & Economic Report-Alumni Program','Winants Hall,College Avenue Campus,New Brunswick,NJ US','2010-12-08 13:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67225','Carl Van Horn is widely recognized as an expert on workforce, human resources and employment policy issues.  He has extensive experience  in public and private  policy making.  ','Career','Alumni','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (719,'Laboratory Safety Training','Cook Campus Center,George H. Cook Campus,Piscataway,NJ US','2010-12-08 13:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66137','Laboratory Safety Training - (NJ Right-to-Know / Hazardous Communication / Chemical Hygiene / RCRA) for all employees and students who work in laboratories where chemicals are used.

** No registration Required **','Other','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (720,'CORE Pesticide Training Program - English Only','Cook Campus Wide,George H. Cook Campus,New Brunswick,NJ US','2010-12-08 12:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65135','The New Jersey Department of Environmental Protection Pesticide Control Program (PCP) pesticide regulations include training requirements for any new commercial applicators and operators.','Workshop, Course','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (721,'Immaculate Conception Mass','Cook Campus Center,George H. Cook Campus,New Brunswick,NJ US','2010-12-08 12:15:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66830','We offer a Mass on every campus','Religious','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (722,'Immaculate Conception Mass','Busch Campus Center,Busch Campus,Piscataway,NJ US','2010-12-08 12:15:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66829','We offer a Mass on every campus','Religious','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (723,'Rutgers Center for Literacy Development Network Meeting: "Grouping for Literacy Instruction:  New Evidence, New Understandings, New Practices"','Off-Campus Location/S,Off Campus Campus,Unknown,NJ US','2010-12-09 00:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67217','The last two decades have seen dramatic shifts in teachers uses of various grouping practicesfrom rigid ability grouping, to whole-class instruction, and now, in many classrooms, a return to forms of ability grouping, this time under the label of guided reading.','Workshop, Course','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (724,'Introduction to Hydraulics','New Brunswick Campus Wide,Multiple Locations Campus,New Brunswick,NJ US','2010-12-09 08:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65863','This new course is designed to cover the basic principles of hydraulics that apply to most trades. ','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (725,'Holyday Mass, Immaculate Conception','Off-Campus Location/S,Off Campus Campus,New Brunswick,NJ US','2010-12-08 12:15:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66828','We offer a Mass on every campus','Religious','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (726,'Immaculate Conception Mass','Livingston Student Center,Livingston Campus,New Brunswick,NJ US','2010-12-08 22:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66833','We offer a Mass on every campus','Religious','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (727,'Immaculate Conception Mass','Off-Campus Location/S,Off Campus Campus,New Brunswick,NJ US','2010-12-08 21:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66836','We offer a Mass on every campus','Religious','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (728,'BINGO Night','Neilson Dining Hall,Douglass Campus,New Brunswick,NJ US','2010-12-08 21:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67794','Play B-I-N-G-O','Special Event','Current Students,Commuters,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (729,'Rutgers Jazz Chamber Ensemble','Marryott Music Building, Stephanie Morris,Douglass Campus,New Brunswick,NJ US','2010-12-08 20:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65943','An intimate evening of jazz','Performance','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (730,'Hazardous Tree Identification','New Brunswick Campus Wide,Multiple Locations Campus,New Brunswick,NJ US','2010-12-10 09:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65889','Hazardous trees pose a double danger. They are tough to recognize, and they can be costly  and even deadly  if not managed before an avoidable accident happens.','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (731,'Mexican Migrants and Their Children: Family Separation in a New Jersey Immigrant Community','Livingston Student Center,Livingston Campus,Piscataway,NJ US','2010-12-08 20:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67637','Joanna Dreby will present on her 4 year ethnographic study with over 140 members of Mexican transnational families in Central New Jersey and the Mixteca region of Oaxaca. Private aspects of family life, she shows, are shaped by larger processes of international migration and parental work patterns.','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (732,'Maternal stress and diet: Intrauterine and early postnatal environment effects on offspring','Foran Hall,George H. Cook Campus,New Brunswick,NJ US','2010-12-10 09:15:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67596','Environmental disturbances during development have significant effects on offspring and increase susceptibility to adult chronic disease.  We use an animal model with a multilevel systems approach to study disease development in response to changes in the early developmental environment.  

','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (733,'Holyday Mass Immaculate Conception','Off-Campus Location/S,Off Campus Campus,New Brunswick,NJ US','2010-12-08 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66835','We offer a Mass on every campus','Religious','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (734,'Sixth Labor & Management Conference','Labor Education Center,George H. Cook Campus,New Brunswick,NJ US','2010-12-10 08:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67237','Panel discussion: Forms of Dispute Resolution and Their Effectiveness; Innovations through Collective Bargaining; Issues of Privatization','Special Event','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (735,'Women''s Basketball vs. Georgetown','Louis Brown Athletic Center (Rac),Livingston Campus,Piscataway,NJ US','2010-12-09 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67369','The Women''s Basketball team will be hosting Central Connecticut State at the RAC Thursday, December, 9th at 7:30 pm.','Sporting Event','Current Students,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (736,'Rutgers Symphony Band','Nicholas Music Center,Douglass Campus,New Brunswick,NJ US','2010-12-09 20:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65934','Darryl Bott, conductor','Performance','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (737,'"Blood Lactate Guided Training in Equine Athletes"','Bartlett Hall,George H. Cook Campus,New Brunswick,NJ US','2010-12-09 19:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67740','The Rutgers Equine Science Center presents guest speaker, Dr. Arno Lindner, to discuss Blood Lactate Guided Training in Equine Athletes on Thursday, December 9, 2010 from 7:00  9:00 pm.  The presentation will be held at Bartlett Hall, Room 123, on G.H. Cook Campus in New Brunswick.','Talk, Lecture, Seminar','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (738,'Rutgers Symphony Orchestra','Nicholas Music Center,Douglass Campus,New Brunswick,NJ US','2010-12-10 20:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65929','A Strauss Affair to Remember: Barber: Symphony No.1, Op.9; Prokofiev: Piano Concerto No.1, Op.10 in D-flat major (featuring Seungmi Jung, piano); Strauss: Metamorphosen; Strauss: Death and Transfiguration
','Performance','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (739,'Rutgers Camden MBA Information Session','Camden College Center,Camden Campus,Camden,NJ US','2010-12-09 17:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65012','An information session for those interested in pursuing an MBA degree from Rutgers Camden.  Opportunity to meet faculty and students. For more info please call 856-225-6452.','Special Event','Prospective Students','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (740,'Organizational Communication Mini-Conference 2010','School Of Communication And Information,College Avenue Campus,New Brunswick,NJ US','2010-12-08 00:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=63792','23rd annual organizational Communication Mini Conference ','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (741,'Mindfulness Meditation','Douglass Campus Center,Douglass Campus,New Brunswick,NJ US','2010-12-09 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66935','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required.','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (742,'Christmas Party','Catholic Center,College Avenue Campus,New Brunswick,NJ US','2010-12-10 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66826','Party before finals! Join us in a pre-Christmas celebration. Free food, music, games and fellowship.','Special Event','Current Students,Undergraduate Students,Graduate Students','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (743,'Holiday Party and Sing-Along with Dee','Rutgers Club,College Avenue Campus,New Brunswick,NJ US','2010-12-10 17:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66782','Holly-Jolly-Folly and please bring some canned goods to donate to a local food pantry. 
Buffet begins at 5:30 and the sleigh bells begin to ring at 6 p.m.','Special Event','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (744,'Professors'' Oriental Abstract World - exhibit opening reception','Voorhees Hall Incl Zimmerli Art Museum,College Avenue Campus,New Brunswick,NJ US','2010-12-10 18:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67441','The "Professors'' Oriental Abstract World" exhibit features the Chinese brush calligraphy and painting artworks of two NJ university professors -  Zhiyuan Cong of William Paterson University and Yi-Zhi Huang of Rutgers University. The opening reception will include demonstrations by both artists.','Art','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (745,'Manganese Nutrition of Glyphosate-Tolerant Crops - Understanding the Controversy','Foran Hall,George H. Cook Campus,New Brunswick,NJ US','2010-12-10 12:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67121','James Cambararo of Purdue will speak on Manganese Nutrition of Glyphosate-Tolerant Crops - Understanding the Controversy.','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (746,'UNIX 1','Davidson Hall,Busch Campus,Busch Campus,Piscataway,NJ US','2010-12-15 09:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67500','Learn to use a UNIX login to your Rutgers account to accomplish tasks','Workshop, Course','Current Students,Commuters,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (747,'On-Farm and Manure Composting School','Off-Campus Location/S,Off Campus Campus,New Brunswick,NJ US','2010-12-13 08:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67355','New rules require New Jersey livestock farmers to develop and implement Animal Waste Management Plans to illustrate the responsible management of manure on their operation. These Plans should have been developed by September 16, 2010 and must be implemented by March 16, 2011.','Workshop, Course','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (748,'Men''s Basketball vs. Fairleigh Dickinson','Louis Brown Athletic Center (Rac),Livingston Campus,Piscataway,NJ US','2010-12-14 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67372','Men''s basketball takes on Fairleigh Dickinson at the RAC at 7:30 pm.','Sporting Event','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (749,'Mindfulness Meditation','Busch Campus Center,Busch Campus,Piscataway,NJ US','2010-12-14 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66871','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required.','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (750,'Equine Science Update','Cook Campus Center,George H. Cook Campus,New Brunswick,NJ US','2010-12-14 18:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67536','The Equine Science Update is an opportunity to unite equine professionals, horse owners, farm owners and stable managers, educators and students, 4-H members, and equine enthusiasts to present the Equine Science Centers research initiatives and work in advancing horse industry issues.','Talk, Lecture, Seminar','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (751,'Rutgers Choral Concert','Bradley Hall,Newark Campus,Newark,NJ US','2010-12-13 11:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66005','Rutgers University Chorus, John floreen, conductor','Performance','Current Students,Visitors,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (752,'Water Management and Drainage','New Brunswick Campus Wide,Multiple Locations Campus,New Brunswick,NJ US','2010-12-14 09:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65898','This one-day course is designed to focus on the drainage problems and repairs of highest value to you, your customers and their plants. ','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (753,'OTC Roundtable Series - Intellectual Ventures Funding Opportunities','Fiber Optic Materials Research Building,Busch Campus,Piscataway,NJ US','2010-12-13 09:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67758','Need funding for Innovation?  Come learn about the newest funding opportunity available to faculty/students with early stage inventions. The Office of Technology Commercialization invites all faculty and students to learn about the new Rutgers IP Development Fund. ','Talk, Lecture, Seminar','Researchers,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (754,'Dodgeball Tournament','College Ave Gym,College Avenue Campus,New Brunswick,NJ US','2010-12-13 20:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67795','Release the Beast Pre-Exam Stress Busting Dodgeball Extravaganza','Special Event','Current Students,Commuters,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (755,'C. elegans evolutionary genomics','Life Sciences Building,Busch Campus,Piscataway,NJ US','2010-12-13 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66420','Dr. Ilya Ruvinsky, Dept. of Ecology and Evolution, University of Chicago, Chicago, IL','Talk, Lecture, Seminar','Current Students,Researchers,Visitors,Donors & Supporters,Undergraduate Students,Graduate Students,Faculty,Staff,Alumni,General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (756,'Christmas in Carol and Song','Kirkpatrick Chapel,College Avenue Campus,New Brunswick,NJ US','2010-12-11 18:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65947','Rutgers Glee Club and Kirkpatrick Choir; Patrick Gardner, conductor','Performance','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (757,'Hutcheson Memorial Forest Tour;" Winter ecology at the forest"','Off-Campus Location/S,Off Campus Campus,Somerset,NJ 08873,NJ US','2010-12-12 14:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66763','There is no charge, and reservations are not required on these guided public tours. Groups of more than ten persons may not attend the guided tours
','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (758,'Rutgers Choral Concert','Off-Campus Location/S,Off Campus Campus,Newark,NJ US','2010-12-12 15:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66002','Rutgers University Chorus, John Floreen, conductor','Performance','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (759,'Men''s Basketball vs. Marquette','Louis Brown Athletic Center (Rac),Livingston Campus,Piscataway,NJ US','2011-01-05 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67374','Men''s basketball takes on Big East opponent Marquette at the RAC at 7:30 pm.','Sporting Event','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (760,'Art after Hours: First Wednesdays','Voorhees Hall Incl Zimmerli Art Museum,College Avenue Campus,New Brunswick,NJ US','2011-01-05 17:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66502','Held on the first Wednesday of every month, Art after Hours complements the museum''s innovative exhibitions with music and dance performances, spotlight tours, poetry slams, film screenings, and more. ','Art','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (761,'Mindfulness Meditation','Rutgers Student Center,College Avenue Campus,New Brunswick,NJ US','2011-01-05 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66906','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required. ','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (762,'Women''s Basketball vs. George Washington','Louis Brown Athletic Center (Rac),Livingston Campus,Piscataway,NJ US','2011-01-03 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67377','The Women''s Basketball team will be hosting George Washing at the RAC Monday, January, 3rd at 7:30 pm.','Sporting Event','Current Students,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (763,'Mindfulness Meditation','Busch Campus Center,Busch Campus,Piscataway,NJ US','2011-01-04 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66873','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required.','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (764,'Basics of Turfgrass Management','New Brunswick Campus Wide,Multiple Locations Campus,New Brunswick,NJ US','2010-12-16 09:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65896','In this highly informative one-day program, you will be introduced to a full range of turfgrass management topics and practices.','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (765,'4 Day - Better Process Control School','Cook Campus Wide,George H. Cook Campus,New Brunswick,NJ US','2010-12-14 08:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66117','Is your canned food product vulnerable to food contamination?  Registering for our four-day Better Process Control School can help you reduce your possible exposure to liability.','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (766,'Holiday Buffet  Lunches','Rutgers Club,College Avenue Campus,New Brunswick,NJ US','2010-12-13 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66783','Carving stations and a groaning board of goodies.','Special Event','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (767,'Turfgrass Establishment','New Brunswick Campus Wide,Multiple Locations Campus,New Brunswick,NJ US','2010-12-17 09:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65897','This one-day course offers specific instruction on how to successfully establish turfgrass. ','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (768,'Operation and Maintenance of Pumps','New Brunswick Campus Wide,Multiple Locations Campus,New Brunswick,NJ US','2010-12-15 08:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65522','Our most popular hands-on course!  You will learn and practice accepted procedures for maintaining pump equipment on both a daily and long-term basis.  ','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (769,'Holiday Lunch Buffet','Continuing Studies Conference Center,Douglass Campus,New Brunswick,NJ US','2010-12-21 11:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67616','Back by popular demand.  Round up your favorite co workers and ring in the holiday season.  Check out our website for detailed menu information and reservation instructions.','Special Event','Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (770,'Mindfulness Meditation','Douglass Campus Center,Douglass Campus,New Brunswick,NJ US','2010-12-16 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66936','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required.','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (771,'Large Tree Climbing and Rigging','New Brunswick Campus Wide,Multiple Locations Campus,New Brunswick,NJ US','2010-12-16 09:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65891','You dont need to sacrifice safety for speed! In this two-day class, discover the techniques that increase your productivity while maintaining the high level of safety that is the mark of a good arborist.','Workshop, Course','General Public','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (772,'Female mate choice in the domesticated goat','Marine Sciences Building,George H. Cook Campus,New Brunswick,NJ US','2010-12-17 13:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66768','Ph.D. dissertation defense seminar','Talk, Lecture, Seminar','no target audience','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (773,'Men''s Basketball vs. St. Peter''s','Louis Brown Athletic Center (Rac),Livingston Campus,Piscataway,NJ US','2010-12-23 19:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67373','Men''s basketball takes on St. Peter''s at the RAC at 7:30 pm.','Sporting Event','Current Students,Researchers,Visitors,Commuters,Donors & Supporters,Undergraduate Students,Graduate Students,Prospective Students,Faculty,Staff,Alumni,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (774,'Mindfulness Meditation','Rutgers Student Center,College Avenue Campus,New Brunswick,NJ US','2010-12-22 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66905','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required. ','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (775,'Free First Sundays','Voorhees Hall Incl Zimmerli Art Museum,College Avenue Campus,New Brunswick,NJ US','2011-01-02 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67479','The first Sunday of every month at the Zimmerli becomes a free day of activities, tours, and fun for the whole family.','Art','Current Students,Visitors,Commuters,Undergraduate Students,Prospective Students,General Public,Parents & Families','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (776,'Mindfulness Meditation','Douglass Campus Center,Douglass Campus,New Brunswick,NJ US','2010-12-23 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66937','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required.','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (777,'Holiday Lunch Buffet','Continuing Studies Conference Center,Douglass Campus,New Brunswick,NJ US','2010-12-22 11:30:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=67617','Back by popular demand.  Round up your favorite co workers and ring in the holiday season.  Check out our website for detailed menu information and reservation instructions.','Special Event','Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (778,'Mindfulness Meditation','Busch Campus Center,Busch Campus,Piscataway,NJ US','2010-12-21 12:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=66872','Mindfulness is the art of becoming a compassionate observer of your own experience. Meditation practice helps us to achieve mindfulness and reduce stress. All are welcome  faculty, staff & students. No previous experience required.','Workshop, Course','Current Students,Undergraduate Students,Graduate Students,Faculty,Staff','hash');
insert into rugoing.events(eventid,name,location,timeofevent,url,synopsis,category,target_audience,hashtag) values (779,'104th Statistical Mechanics Conference','Hill Center Bldg For The Mathematical Sciences,Busch Campus,Piscataway,NJ US','2010-12-19 08:00:00','http://ruevents.rutgers.edu/events/displayEvent.html?eventId=65956','http://www.math.rutgers.edu/events/smm/index.html','Meeting','Current Students,Researchers,Visitors,Donors & Supporters,Undergraduate Students,Graduate Students,Faculty,Alumni,General Public','hash');
